version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: daily
      open-pull-requests-limit: 5
      ignore:
          - dependency-name: '*'
            update-types: ["version-update:semver-minor", "version-update:semver-patch"]
          # node support !== >=12.10.0
          - dependency-name: 'mocha'
            versions: ['>=10']
            update-types: ["version-update:semver-minor", "version-update:semver-patch"]
          - dependency-name: 'sinon'
            versions: ['>=14']
            update-types: ["version-update:semver-minor", "version-update:semver-patch"]
          # ESM only version
          - dependency-name: 'dargs'
            versions: ['>=8']
            update-types: ["version-update:semver-minor", "version-update:semver-patch"]
          - dependency-name: 'execa'
            versions: ['>=6']
            update-types: ["version-update:semver-minor", "version-update:semver-patch"]
          - dependency-name: 'read-pkg-up'
            versions: ['>=8']
            update-types: ["version-update:semver-minor", "version-update:semver-patch"]
          - dependency-name: 'sort-keys'
            versions: ['>=5']
            update-types: ["version-update:semver-minor", "version-update:semver-patch"]
          - dependency-name: 'chalk'
            versions: ['>=5']
            update-types: ["version-update:semver-minor", "version-update:semver-patch"]

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 5
